services:
  initial_data:
    build:
      context: ..
      dockerfile: docker/Dockerfile.initial
      ssh:
        - default
    container_name: initial_data_generator
    restart: "no"
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ${HOST_DATA_DIR}:/app/data
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/data/customers.csv && test -f /app/data/accounts.csv"]
      interval: 10s
      timeout: 5s
      retries: 5

  automator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.automator
      ssh:
        - default
    env_file:
      - .env
    container_name: data_automator
    depends_on:
      initial_data:
        condition: service_completed_successfully
    environment:
      - DATA_DIR=/app/data
    volumes:
      - ${HOST_DATA_DIR}:/app/data
