name: Build Docker Containers

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # If you're using SSH forwarding for private repos, you can enable it here.
      # Ensure your SSH key is added as a secret (e.g., SSH_PRIVATE_KEY) and then use:
      - name: Configure SSH for BuildKit
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker Containers
        run: docker-compose -f docker/docker-compose.yaml -p data_generator up --build -d

      - name: List Built Images
        run: docker images
